# Generated by Django 5.2.16 on 2026-07-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('joined_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
