"""
Django settings for training_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gv$bd&t#swsw_v-=3b--))!agr2em!)6_51kv1#!*b5v73uuis'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'student'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'training_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'training_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        # Day 4 - Task 2: Custom strong-password validator
        # Requires uppercase, lowercase, digit and special character.
        'NAME': 'student.validators.StrongPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Authentication Settings ────────────────────────────────────────────────────
# Unauthenticated users are sent to /login/
LOGIN_URL = '/login/'
# After successful login (fallback if no 'next' param) — views handle per-role redirect
LOGIN_REDIRECT_URL = '/student/'
# After logout
LOGOUT_REDIRECT_URL = '/'

# ── Session / Cookie Security (Day 4 - Task 2) ───────────────────────────────
# HTTPOnly: JS cannot read the session cookie — prevents XSS token theft
SESSION_COOKIE_HTTPONLY = True
# Close browser → session cookie is cleared (no persistent logins)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Max session lifetime in seconds (1 hour)
SESSION_COOKIE_AGE = 3600
# NOTE: SESSION_COOKIE_SECURE and CSRF_COOKIE_SECURE must only be True on HTTPS.
# Enabling them on local HTTP (DEBUG=True) will break the login flow because the
# browser will refuse to send the cookies over plain HTTP.
# SESSION_COOKIE_SECURE = True   # Uncomment only in HTTPS production
# CSRF_COOKIE_SECURE    = True   # Uncomment only in HTTPS production

# ── Email Backend (Day 4 - Task 2: Password Reset) ───────────────────────────
# Console backend prints emails to the terminal during development.
# Replace with smtp.EmailBackend and SMTP credentials for production.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@trainingportal.com'
