# Generated by Django 5.2.11 on 2026-07-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("age", models.IntegerField()),
                ("course", models.CharField(max_length=100)),
                ("marks", models.IntegerField()),
                ("join_date", models.DateField()),
                ("active_status", models.CharField(max_length=50)),
            ],
        ),
    ]
