# Generated by Django 5.2.11 on 2026-07-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_course_department_remove_student_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ManyToManyField(related_name="students", to="students.course"),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="students.department",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="phone",
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="students.student",
            ),
        ),
    ]
