# Generated by Django 5.2.11 on 2026-07-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_age_alter_student_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="age",
        ),
    ]
