# Generated by Django 6.1 on 2026-09-16 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_feedback_markhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='requested_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_requests', to='students.course'),
        ),
    ]
