# Generated by Django 5.2.11 on 2026-07-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_remove_student_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="DoB",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="address",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="phone",
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
