# Generated by Django 6.1 on 2026-09-16 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_userprofile_requested_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
