# Generated by Django 6.1 on 2026-09-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_course_duration_days_enrollment_enrolled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
