# Generated by Django 5.2.11 on 2026-07-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
