# Generated by Django 5.2.10 on 2026-09-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_userprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
