# Generated by Django 5.2.11 on 2026-07-28 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_alter_studentprofile_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_trainer",
                        to="students.course",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        limit_choices_to={"role": "TRAINER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_course",
                        to="students.userprofile",
                    ),
                ),
            ],
        ),
    ]
