# Generated by Django 6.1 on 2026-09-21 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='markhistory',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mark_history', to='students.enrollment'),
        ),
        migrations.AlterField(
            model_name='trainercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_assignments', to='students.course'),
        ),
        migrations.AlterField(
            model_name='trainercourse',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
