# Generated by Django 5.2.11 on 2026-07-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_trainercourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="account_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="failed_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
