# Generated by Django 5.2.11 on 2026-07-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_userprofile_account_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
