# Generated by Django 5.1.4 on 2026-08-17 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_course_code_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='markshistory',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marks_history', to='students.enrollment'),
        ),
    ]
