# Generated by Django 5.2.10 on 2026-09-16 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auditlog_affected_object_auditlog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='students.course'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
