# Generated by Django 6.0.7 on 2026-09-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auditlog_affected_object_auditlog_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
