# Generated by Django 6.0.7 on 2026-09-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
