# Generated by Django 5.2.10 on 2026-09-16 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_feedback_course_feedback_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_marks', models.PositiveIntegerField()),
                ('new_marks', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_history', to='students.student')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
