# Generated by Django 5.1.4 on 2026-08-17 07:49

import django.core.validators
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_feedback_enrollment_markshistory_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(validators=[students.models.validate_date_of_birth]),
        ),
    ]
