# Generated by Django 6.0.7 on 2026-10-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auditlog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='date',
        ),
    ]
