# Generated by Django 5.2.11 on 2026-07-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_auditlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditlog",
            old_name="descrption",
            new_name="description",
        ),
    ]
