# Generated by Django 5.1.4 on 2026-08-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_feedback_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
