# Generated by Django 5.1.4 on 2026-08-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
