# Generated by Django 5.1.4 on 2026-08-17 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='marks',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
