# Generated by Django 5.1.4 on 2026-08-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_enrollment_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
    ]
