"""add idempotency key to jobs

Revision ID: 00f297d7b0d1
Revises: 278c38b58aa7
Create Date: 2026-10-07 08:30:08.229001

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00f297d7b0d1"
down_revision: str | Sequence[str] | None = "278c38b58aa7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("idempotency_key", sa.String(length=255), nullable=True)
    )
    op.create_unique_constraint("uq_jobs_idempotency_key", "jobs", ["idempotency_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_jobs_idempotency_key", "jobs", type_="unique")
    op.drop_column("jobs", "idempotency_key")
    # ### end Alembic commands ###
