"""create jobs table

Revision ID: 278c38b58aa7
Revises: b6ab5b244106
Create Date: 2026-10-06 10:06:54.653232

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "278c38b58aa7"
down_revision: str | Sequence[str] | None = "b6ab5b244106"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
