"""
Django settings for training_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!56iqi0e#@(b4-&z@nyjli3yr1*edqrrkl-qc_13$@1=m51^$s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'students',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'training_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'training_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        # Covers "password must not match username or email" -- it checks
        # the new password against several User attributes, including
        # username and email, and rejects passwords that are too similar.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        # Custom validator (students/validators.py): requires at least one
        # uppercase letter, one lowercase letter, one digit, and one
        # special character.
        'NAME': 'students.validators.ComplexityValidator',
    },
]


# Email
# https://docs.djangoproject.com/en/6.0/topics/email/
#
# Console backend for local development: password-reset emails are printed
# to the terminal running `runserver` instead of actually being sent. Swap
# this for a real backend (SMTP, SES, SendGrid, etc.) in production.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'training-portal@example.com'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Messages framework - use session storage so messages work without extra setup
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Authentication redirects
LOGIN_URL = 'login'
# Every login goes through this dispatcher view first, which then sends the
# user on to the dashboard matching their role (admin / trainer / student).
LOGIN_REDIRECT_URL = 'post_login_redirect'
LOGOUT_REDIRECT_URL = 'login'


# Session and cookie security
# https://docs.djangoproject.com/en/6.0/ref/settings/#session-cookie-httponly
#
# SESSION_COOKIE_HTTPONLY: safe to enable everywhere, including local HTTP
# development -- it stops JavaScript from reading the session cookie
# (mitigates cookie theft via XSS) and has no dependency on HTTPS.
SESSION_COOKIE_HTTPONLY = True

# SESSION_COOKIE_SECURE / CSRF_COOKIE_SECURE: these tell the browser to
# *never* send the cookie over plain HTTP. They REQUIRE the site to be
# served over HTTPS. Enabling them while running `manage.py runserver` on
# plain http://127.0.0.1:8000 will silently break login (the cookie is set,
# but the browser refuses to send it back on the next request), so they are
# left False here for local development and should only be switched to True
# in a production settings file once the site is actually served over
# HTTPS (e.g. behind an SSL-terminating load balancer or reverse proxy).
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# SESSION_EXPIRE_AT_BROWSER_CLOSE / SESSION_COOKIE_AGE: safe to use locally.
# Sessions here expire after 2 hours of the cookie's age, and also end when
# the browser is closed -- a reasonable default for a training portal that
# handles student marks and personal feedback.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 60 * 2  # 2 hours
