"""allow task history after task deletion

Revision ID: 850f6e120ebc
Revises: 2805b51259cc
Create Date: 2026-09-29 18:13:19.926053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850f6e120ebc'
down_revision: Union[str, Sequence[str], None] = '2805b51259cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_history', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('task_history_task_id_fkey'), 'task_history', type_='foreignkey')
    op.create_foreign_key(
    'task_history_task_id_fkey',
    'task_history',
    'tasks',
    ['task_id'],
    ['id'],
    ondelete='SET NULL',
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.create_foreign_key(op.f('task_history_task_id_fkey'), 'task_history', 'tasks', ['task_id'], ['id'])
    op.alter_column('task_history', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
