# Generated by Django 6.1.1 on 2026-09-08 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("age", models.PositiveIntegerField()),
                ("course", models.CharField(max_length=20)),
                ("marks", models.PositiveIntegerField()),
                ("joined_date", models.DateField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="student.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.TextField()),
                ("code", models.CharField()),
                ("duration", models.IntegerField(help_text="Duration in Months")),
                ("active_status", models.BooleanField(default=True)),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="courses", to="student.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.IntegerField(verbose_name=10)),
                ("address", models.TextField()),
                ("date_of_birth", models.DateTimeField(blank=True, null=True)),
                (
                    "students",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to="student.student",
                    ),
                ),
            ],
        ),
    ]
