# Generated by Django 6.1.1 on 2026-09-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="active_status",
            new_name="active",
        ),
    ]
