# Generated by Django 6.1.1 on 2026-09-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_loginattempt_userprofile_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="phone",
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
