# Generated by Django 5.2.8 on 2026-08-09 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_trainer_auditlog_feedback_markshistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__role': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
