# Generated by Django 6.1.1 on 2026-09-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_auditlog_action_type_auditlog_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
